### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xfally** [comment]
Arg `-p` is necessary to make sure the path exists, as some Linux distribution (e.g. Ubuntu) doesn't have ~/bin directory by default after installed.

**Comment by ghost** [comment]
isn't `-p` is to make sub directory right away
 eg, `mkdir -p ~/bin/subdir`?

I tried it without `-p` flag, still working.

and the pr, only delete cd'ing' into $P, because you did the operations with $P and ~/. cd into $P became unecessary.

I know this won't matter, but I love to discuss this, so I can get which is the right way to do it.

UPDATE: I do realize from the `man` of mkdir, where it stated `-p, --parents
              no error if existing, make parent directories as needed`. So how this working? mkdir ~/bin doesn't give you error if the dir already exist, and so with the supplied `-p` flag.



Also, one more question, I didn't try this xgrep tool yet. So what is the difference between `grep -r [PATTERN] [FILE]` and xgrep?

**Comment by xfally** [comment]
Ah, `man` is right, and my last answer is not quite right. It's my best practice to add `-p` always, so have no need to care about the parent directory exist or not. But you can remove `-p` surely, and stood on your own opinion.

`cd $P` is unnecessary. I forgot to delete it when copied from my other codes.

`xgrep` is an encapsulation of native `grep` and `find` commands. The scripts are created to make daily work easier.

**Comment by ghost** [comment]
Oh I see, thanks. Gonna  try it out.

**Comment by xfally** [comment]
I have deleted `cd $P` (via `git push -f` to update `master` branch, so this PR is not needed).

If you like the scripts, you should re-fork the project to sync the update.

**Pull request closed without merging**
